config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, only: [:edit, :new, :create, :destroy, :index, :show, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ApplicationRecord
  # include ActiveView::DateHelpers
  validates :color, inclusion: { in: %w(brown white gray black orange 
    spotted striped), message: "#{:color} is not a natural color" }

  validates :birth_date, :name, :sex, :color, :description,  presence: true

  validates :sex, inclusion: { in: %w(M F X), message: "#{:sex} is not a valid sex" }
    
  def age
    @age ||= (1..10).sample
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])

    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render json: @cat.errors.full_messages, status: 422
    end
  end

  private 
  def cat_params
    params.require(:cat).permit(:name, :birth_date, :color, :sex, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cats/edit.html.erb
  <% action_url = cat_url(@cat) %>
  <% button_text = 'Update Cat' %>

<form action="<%= action_url %>" method="post">

<input type="hidden" name="_method" value="patch">

  <label for="name">Name:
    <input type="text" id="name" name="cat[name]" 
          value="<%= @cat.name %>">
  </label>
  <br>
  <label for="birth_date">Birth Date:
    <input type="date" id="birth_date" name="cat[birth_date]" 
          value="<%= @cat.birth_date %>">
  </label> 
  <br>
  <select name="cat[color]">
    <option value="brown">Brown</option>
    <option value="white">White</option>
    <option value="gray">Gray</option>
    <option value="black">Black</option>
    <option value="orange">Orange</option>
    <option value="spotted">Spotted</option>
    <option value="striped">Striped</option>
</select>
  <br>
  <label for="sex">Sex:
    <input type="radio" name="cat[sex]" value="M"> Male<br>
    <input type="radio" name="cat[sex]" value="F"> Female<br>
    <input type="radio" name="cat[sex]" value="X"> Other
 
  </label>
  <label for="description">Description:
    <input type="text" id="description" name="cat[description]" 
          value="<%= @cat.description %>">
  </label>
  <br>
  <input type="submit" value="<%= button_text %>">
</form>

app/views/cats/index.html.erb
<h2> Cats! </h2>

<% @cats.each do |cat| %>
<ul>
  <li><a href="<%= cat_url(cat) %>"><%= cat.name %></a></li>
    <ul>
    <li><%= cat.birth_date %></li>
    <li><%= cat.color %></li>
    <li><%= cat.sex %></li>
    <li><%= cat.description %></li>
    </ul>
</ul>
<% end %>


 

app/views/cats/new.html.erb
  <% action_url = cats_url %>
  <% button_text = 'Create Cat' %>

<form action="<%= action_url %>" method="post">
  <label for="name">Name:
    <input type="text" id="name" name="cat[name]" 
          value="<%= @cat.name %>">
  </label>
  <br>
  <label for="birth_date">Birth Date:
    <input type="date" id="birth_date" name="cat[birth_date]" 
          value="<%= @cat.birth_date %>">
  </label> 
  <br>
  <select name="cat[color]">
    <option value="brown">Brown</option>
    <option value="white">White</option>
    <option value="gray">Gray</option>
    <option value="black">Black</option>
    <option value="orange">Orange</option>
    <option value="spotted">Spotted</option>
    <option value="striped">Striped</option>
</select>
  <br>
  <label for="sex">Sex:
    <input type="radio" name="cat[sex]" value="M"> Male<br>
    <input type="radio" name="cat[sex]" value="F"> Female<br>
    <input type="radio" name="cat[sex]" value="X"> Other
 
  </label>
  <label for="description">Description:
    <input type="text" id="description" name="cat[description]" 
          value="<%= @cat.description %>">
  </label>
  <br>
  <input type="submit" value="<%= button_text %>">
</form>

app/views/cats/show.html.erb
<h2><a href="<%=edit_cat_url(@cat) %>"><%= @cat.name %></a></h2>

<ul>
    <li><%= @cat.birth_date %></li>
    <li><%= @cat.color %></li>
    <li><%= @cat.sex %></li>
    <li><%= @cat.description %></li>
</ul>
<>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ninetyninecats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>